spec:
  template:
    spec:
      containers:
      - name: vertx
        env:
        - name: JAEGER_SERVICE_NAME
          value: ${project.artifactId}
        - name: JAEGER_REPORTER_LOG_SPANS
          value: true
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: 1
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector:14268/api/traces
      # - name: jaeger-agent
      #   image: jaegertracing/jaeger-agent:1.6
      #   args: ["--collector.host-port=jaeger-collector:14267"]
      #   ports:
      #   - containerPort: 6831
      #     protocol: UDP
